### ISSUE TITLE
extra `<?xml version="1.0" encoding="utf-8"?>` is added to dotNetCoreVersions.props

### ISSUE THREAD

**Issue by wli3** [dotnet/insertions-client#10]
![image](https://user-images.githubusercontent.com/6993335/83696633-ce783400-a5b1-11ea-9620-f7f9bcc2bc50.png)

**Comment by joeloff** [comment]
I'm still seeing this issue

![image](https://user-images.githubusercontent.com/7409981/86276949-b08af880-bb8a-11ea-9b9c-d01a2c66fe2f.png)

**Comment by bekir-ozturk** [comment]
Update: it is not the xml header being added to the file, but byte order mark for UTF-8. Can you just push it or should this file stay ASCII encoded?

--

@joeloff Have you pulled the fix and rebuilt your executable?

You can also directly get the tool without dealing with the repo:
`PS> dotnet tool install -g Microsoft.DotNet.InsertionsClient.Console --version 1.0.*-*`
then use as
`PS> InsertionsCilent <your args>`
if you have dotnet-eng feed in your Nuget.Config
`https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json`.

**Comment by joeloff** [comment]
I'll try that. I noticed that the tool moved to a different location under dotnet (the internal documentation still pointed to this repo instead of (https://github.com/dotnet/insertions-client)
