### ISSUE TITLE
Do not edit encoding

### ISSUE THREAD

**Issue by wli3** [dotnet/insertions-client#13]
https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/263836?iteration=3&base=2&_a=files
![image](https://user-images.githubusercontent.com/6993335/89135554-421bbc00-d4e3-11ea-8c0e-29a8df8b75cb.png)

I filed a bug to keep the encoding before. But this is adding the encoding string. I think you need to check if there is an encoding first without editing it and then keep the encoding/not having the encoding when save.

**Comment by wli3** [comment]
@bozturkMSFT

**Comment by donJoseLuis** [comment]
@wli3 thanks for the issue.  Can you please comment on the impact of this issue?  What would happen if we didn't fix it?

**Comment by wli3** [comment]
Part of the insertion cannot be automated. Someone need to manually revert all the changed xmls. However, since this breaks the automation, it will add about 20 minutes for every insertion (average once every week). We also have to maintained a documentation and train new people or vendors every time. That is also significate.

At the same time. I believe your team at this point should have a good understanding of the insertion process. You should be able to understand the impact by the issue description. Let me know if it is not this case. If not, we need to be on the same page.

**Comment by bekir-ozturk** [comment]
Hi @wli3 
 I have failed to reproduce this, running the tool on the same VS commit that your PR originates from.
 Can you share the log file that was created during the run? What is the locale and OS of the machine running the tool? Are you sure you are using the latest version of the tool?

**Comment by wli3** [comment]
Could you talk to Jason? Who created the PR.

**Comment by bekir-ozturk** [comment]
We have failed to reproduce the issue. There is a chance that the unwanted changes were introduced with an older version of the tool. Closing.
