### ISSUE TITLE
Update msi install sizes

### ISSUE THREAD

**Issue by bekir-ozturk** [dotnet/insertions-client#5]
Copied from https://github.com/bozturkMSFT/insertions-client/issues/30

Visual Studio Installer shows users how much disk space is needed to install each component.
Swr files should be updated to reflect the install size during insertion.

One of the ways to solve this:
- extract nuget packages
- calculate the install size of msi files.
- determine which swr file needs updating (or which property to update)
- update the swr (or the .props file which defines the propery)

Exit criteria:
- When the tool is run, correct files should be updated with correct install sizes
- A failure during this stage should fail the whole process. No files should change on disk (not even default.config and .packageconfig files).
- Add test cases
- Update README and help texts to reflect the changes

**Comment by donJoseLuis** [comment]
@bozturkMSFT greetings.  Can you please estimate this item?

**Comment by bekir-ozturk** [comment]
@donJoseLuis  ~4 days would be my estimate.

From the original issue:
>What is the impact of "not solving this" in or out of this tool?

This can be an issue on machines with small disk space when installing the SDK through Visual Studio installer, but I am not aware of any complaints about install sizes. So it is my guess that the impact will be minimal.

On the other hand, I believe we need to do this eventually. It is expected as part of VS package authoring, an insertion is not a 100% complete without it, and there is no better place/time to do it.

**Comment by donJoseLuis** [comment]
We are no longer actively investing in this area.
